image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

default:
  tags:
    - k8srunner

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - lint
  - build
  - test
  - publish
  - pages

# Enable caching for python
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cache/pip

# include:
#   # Python
#   - project: "ska-telescope/templates-repository"
#     file: "gitlab-ci/includes/python.gitlab-ci.yml"

# Python lint stage template

chiara-lint:
  image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE
  stage: lint
  tags:
    - k8srunner
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile"; exit 1;)'
    - 'make help | grep python-lint'
    - 'echo "python-lint: installing tools"; time pip3 install poetry black isort pylint-junit'
    - poetry config virtualenvs.create true
    - poetry env use 3.8.1
    - |
      if [[ -f pyproject.toml ]]; then
        echo "python-lint: Installing with poetry";
        time poetry install --no-root;
      else
        if  [[ -f requirements.txt ]]; then
          echo "python-lint: Installing with pip";
          time pip3 install -r requirements.txt;
        fi;
      fi;
  script:
    - make python-lint;
  artifacts:
    paths:
      - build/
    when: always
  rules:
    - exists:
        - pyproject.toml
        - setup.py
